<?php

namespace Database\Seeders;

use App\Models\Account;
use App\Models\ActivityLog;
use App\Models\Budget;
use App\Models\Category;
use App\Models\CategoryBudget;
use App\Models\Expense;
use App\Models\Income;
use App\Models\RecurringExpense;
use App\Models\Tag;
use App\Models\Transfer;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DummyDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::where('role', 'admin')->first();
        if (!$user) {
            $this->command->info('Admin user not found. Skipping dummy data seeding.');
            return;
        }

        $userId = $user->id;

        // 1. Create Accounts
        $accountsData = [
            ['name' => 'HDFC Bank', 'type' => 'bank', 'balance' => 50000, 'icon' => 'fa-building-columns', 'color' => '#1e40af'],
            ['name' => 'Cash Wallet', 'type' => 'cash', 'balance' => 5000, 'icon' => 'fa-money-bill-wave', 'color' => '#166534'],
            ['name' => 'Paytm / Digital', 'type' => 'digital', 'balance' => 2000, 'icon' => 'fa-wallet', 'color' => '#0369a1'],
        ];

        foreach ($accountsData as $acc) {
            Account::updateOrCreate(
                ['user_id' => $userId, 'name' => $acc['name']],
                $acc
            );
        }

        $accounts = Account::where('user_id', $userId)->get();
        $bankAcc = $accounts->where('type', 'bank')->first();
        
        // 2. Create Tags
        $tagsData = ['Office', 'Travel', 'Personal', 'Emergency', 'Leisure', 'Bill'];
        foreach ($tagsData as $tagName) {
            Tag::firstOrCreate(['user_id' => $userId, 'name' => $tagName]);
        }
        $tags = Tag::where('user_id', $userId)->get();

        // 3. Get Categories
        $incomeCategories = Category::where('type', 'income')->get();
        $expenseCategories = Category::where('type', 'expense')->get();

        // 4. Create Incomes (Last 60 days)
        for ($i = 0; $i < 10; $i++) {
            Income::create([
                'user_id' => $userId,
                'account_id' => $bankAcc->id,
                'category_id' => $incomeCategories->random()->id,
                'amount' => rand(5000, 25000),
                'description' => 'Demo Income ' . ($i + 1),
                'income_date' => Carbon::now()->subDays(rand(0, 60)),
                'reference' => 'TXN' . rand(10000, 99999),
            ]);
        }

        // 5. Create Expenses (Last 60 days)
        for ($i = 0; $i < 30; $i++) {
            $expense = Expense::create([
                'user_id' => $userId,
                'account_id' => $accounts->random()->id,
                'category_id' => $expenseCategories->random()->id,
                'amount' => rand(50, 3000),
                'description' => 'Demo Expense ' . ($i + 1),
                'expense_date' => Carbon::now()->subDays(rand(0, 60)),
                'notes' => 'Generated by DummyDataSeeder',
            ]);
            
            // Attach random tags
            $expense->tags()->attach($tags->random(rand(1, 2))->pluck('id'));
        }

        // 6. Create Transfers
        for ($i = 0; $i < 5; $i++) {
            $from = $accounts->random();
            $to = $accounts->where('id', '!=', $from->id)->random();
            
            Transfer::create([
                'user_id' => $userId,
                'from_account_id' => $from->id,
                'to_account_id' => $to->id,
                'amount' => rand(100, 1000),
                'description' => 'Transfer between accounts ' . ($i + 1),
                'transfer_date' => Carbon::now()->subDays(rand(0, 30)),
            ]);
        }

        // 7. Create Budgets
        // Current Month
        $budget = Budget::create([
            'user_id' => $userId,
            'name' => 'Monthly Budget ' . Carbon::now()->format('F'),
            'amount' => 40000,
            'month' => Carbon::now()->month,
            'year' => Carbon::now()->year,
            'type' => 'monthly',
            'start_date' => Carbon::now()->startOfMonth(),
            'end_date' => Carbon::now()->endOfMonth(),
        ]);

        foreach ($expenseCategories->random(5) as $cat) {
            CategoryBudget::create([
                'budget_id' => $budget->id,
                'category_id' => $cat->id,
                'amount' => rand(2000, 8000),
            ]);
        }

        // 8. Recurring Expenses
        RecurringExpense::create([
            'user_id' => $userId,
            'account_id' => $bankAcc->id,
            'category_id' => $expenseCategories->where('name', 'Rent')->first()->id ?? $expenseCategories->first()->id,
            'amount' => 15000,
            'description' => 'Apartment Rent',
            'frequency' => 'monthly',
            'next_due_date' => Carbon::now()->addMonth()->startOfMonth(),
            'is_active' => true,
        ]);

        RecurringExpense::create([
            'user_id' => $userId,
            'account_id' => $bankAcc->id,
            'category_id' => $expenseCategories->where('name', 'Subscriptions')->first()->id ?? $expenseCategories->first()->id,
            'amount' => 699,
            'description' => 'Netflix Premium',
            'frequency' => 'monthly',
            'next_due_date' => Carbon::now()->addDays(15),
            'is_active' => true,
        ]);

        // 9. Create a Group and Memberships
        $buddy = User::where('email', 'buddy@spendwise.com')->first();
        if ($buddy) {
            $group = \App\Models\Group::create([
                'name' => 'Goa Trip',
                'description' => 'Expenses for the Goa trip 2026',
                'user_id' => $userId,
                'invite_code' => \Illuminate\Support\Str::random(8),
            ]);

            \App\Models\GroupMember::create([
                'group_id' => $group->id,
                'user_id' => $userId,
                'role' => 'admin',
                'status' => 'active',
                'joined_at' => Carbon::now(),
            ]);

            \App\Models\GroupMember::create([
                'group_id' => $group->id,
                'user_id' => $buddy->id,
                'role' => 'member',
                'status' => 'active',
                'joined_at' => Carbon::now(),
            ]);

            // Group Expenses
            $groupExpense = \App\Models\GroupExpense::create([
                'group_id' => $group->id,
                'paid_by' => $userId,
                'amount' => 5000,
                'description' => 'Hotel Booking',
                'expense_date' => Carbon::now(),
                'split_type' => 'equal', // 50/50
            ]);

            \App\Models\GroupExpenseSplit::create(['group_expense_id' => $groupExpense->id, 'user_id' => $userId, 'amount' => 2500]);
            \App\Models\GroupExpenseSplit::create(['group_expense_id' => $groupExpense->id, 'user_id' => $buddy->id, 'amount' => 2500]);
            
            // Settlement tracking behind the scenes creates balances (Admin resolves this in GroupSettlementController inherently)
        }

        // 10. Alert Rules
        \App\Models\AlertRule::create([
            'user_id' => $userId,
            'type' => 'large_expense',
            'conditions' => ['threshold' => 10000],
            'is_active' => true,
        ]);

        \App\Models\AlertRule::create([
            'user_id' => $userId,
            'type' => 'low_balance',
            'conditions' => ['threshold' => 1000],
            'is_active' => true,
        ]);

        \App\Models\AlertRule::create([
            'user_id' => $userId,
            'type' => 'budget_threshold',
            'conditions' => ['percentage' => 80],
            'is_active' => true,
        ]);

        // 11. Activity Logs
        ActivityLog::create([
            'user_id' => $userId,
            'action' => 'seed',
            'model_type' => 'System',
            'model_id' => 1,
            'new_values' => ['message' => 'Full dummy data set generated'],
            'ip_address' => '127.0.0.1',
            'user_agent' => 'Console/Seeder',
        ]);

        $this->command->info('Dummy data seeded successfully for User ID: ' . $userId);
    }
}
